module.exports = {
  study_sidebar: [
    'introduction', // 文档 id / 文件名，简写方式
    {
      type: 'category', // 创建层级菜单
      // type: 'link', // 外链（站内站外都可以），路由跳转，需指定 href 属性
      // type: 'ref', // 跳转至文档页面，但是该文档页面不会在侧边菜单栏中显示，需指定文档 id
      // type: 'doc', // 跳转至文档页面，该文档页面会自动在侧边菜单栏中显示，需指定文档 id，一般情况下，都采用简写方式
      // type: 'autogenerated', // 根据目录结构自动生成侧边菜单栏，需指定 dirName 属性
      // id: '', // 文档 id
      // href: '/', // 路由跳转地址
      // dirName: '/',  // 指定文档根目录，用于自动生成侧边菜单栏，可自行配置菜单显示的顺序，1 - 在文档名的前缀添加数字；2 - 配置 _category_.json 文件，设置 position 属性
      label: 'HTML & CSS', // 菜单名称
      collapsible: true, // 是否可以（显示）展开或折叠操作，true - 显示（默认），false - 隐藏
      collapsed: false, // 初始状态（刷新页面）时该菜单是否展开（false）/折叠（true，默认），当不需要该属性时，可以采用简写方式
      items: ['study/html-css/css-grid'], // 子菜单
    },
    {
      type: 'category',
      label: 'JavaScript',
      collapsed: false,
      items: ['study/js/js-tools-function'],
    },
    { React: [] },
  ],
  column_sidebar: [
    {
      type: 'category',
      label: 'Docusaurus 专栏',
      collapsed: false,
      items: ['column-docusaurus/docs-domain', 'column-docusaurus/blog-domain'],
    },
    { 'CSS特效 🤖': [] },
  ],
};
