/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  study: [{ type: 'autogenerated', dirName: 'study' }],
  columns: [
    'introduction',
    {
      type: 'category',
      label: 'Docusaurus 专栏',
      link: {
        type: 'generated-index',
        title: 'Docusaurus 专栏',
        description: '学习 Docusaurus 相关的知识, 包括文档, 博客, 配置等! 🐣',
        slug: '/column-docusaurus/guides',
      },
      // collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'column-docusaurus' }],
    },
    {
      type: 'category',
      label: 'JavaScript 专栏',
      items: [{ type: 'autogenerated', dirName: 'column-js' }],
    },
    {
      type: 'category',
      label: 'CSS 专栏',
      items: [{ type: 'autogenerated', dirName: 'column-css' }],
    },
    { type: 'link', label: '百度一下', href: 'https://www.baidu.com/' },
  ],
};

module.exports = sidebars;
