/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  studySidebar: [
    'introduction',
    {
      type: 'category',
      label: 'HTML & CSS',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'column-js-tools' }],
    },
    {
      type: 'category',
      label: 'JavaScript',
      // collapsed: false,
      items: ['study/js/js-tools-function'],
    },
  ],
  columnSidebar: [
    {
      type: 'category',
      label: 'Docusaurus 专栏',
      link: {
        type: 'generated-index',
        title: 'Docusaurus 专栏',
        description: '学习 Docusaurus 相关的知识，包括文档，博客，配置等! 🐣',
        slug: '/column-docusaurus/guides',
      },
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'column-docusaurus' }],
    },
    { 'CSS专栏 🤖': [{ type: 'autogenerated', dirName: 'column-css' }] },
    { type: 'link', label: '百度一下', href: 'http://baidu.com' },
  ],
};

module.exports = sidebars;
